project_id = "vcgyiyrboumimwgdsitf"

[functions.public-context]
verify_jwt = false

[functions.public-catalog]
verify_jwt = false

[functions.public-availability]
verify_jwt = false

[functions.public-booking]
verify_jwt = false

[functions.public-booking-manage]
verify_jwt = false

[functions.public-booking-cancel]
verify_jwt = false

[functions.public-booking-lookup]
verify_jwt = false
